### ISSUE TITLE
cannot find module 'tunnel' error

### ISSUE THREAD

**Issue by ikappaki** [jcs090218/setup-emacs-windows#223]
Hi,

I've started getting the following today while testing my workflow on github. Perhaps because of a recent change? it happens with any version, thanks!

```
Run jcs090218/setup-emacs-windows@master
  with:
    version: 28.1
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'tunnel'
Require stack:
- D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.669 (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:6333:33)
    at __nccwpck_require__ (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:6464:43)
    at Object.404 (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:1029:29)
    at __nccwpck_require__ (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:6464:43)
    at Object.41 (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:497:23)
    at __nccwpck_require__ (D:\a\_actions\jcs090218\setup-emacs-windows\master\dist\index.js:6464:43) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\a\\_actions\\jcs090218\\setup-emacs-windows\\master\\dist\\index.js'
  ]
}
```

**Comment by ikappaki** [comment]
Definitely an issue with the last commit, a previous commit works:

```
Run jcs090218/setup-emacs-windows@27a991f7e7122b0b997e36c31f7a34a4901e8219
Installing Emacs
c:\emacs\emacs-28.1\bin\emacs.exe --version
GNU Emacs 28.1
```

**Comment by jcs090218** [comment]
I have reverted with 6e1ba035e1387639a42f4ef4872598c88481c863. See if that works?

**Comment by ikappaki** [comment]
> I have reverted with [6e1ba03](https://github.com/jcs090218/setup-emacs-windows/commit/6e1ba035e1387639a42f4ef4872598c88481c863). See if that works?

Yes it worked thanks!

```
Run jcs090218/setup-emacs-windows@master
  with:
    version: 28.1
Installing Emacs
c:\emacs\emacs-28.1\bin\emacs.exe --version
GNU Emacs 28.1
```

**Comment by jcs090218** [comment]
Awesome! Sorry for the inconvenience!
